# Generated by Django 2.2.5 on 2019-10-07 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_select_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='fri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(default=True)),
                ('lunch', models.BooleanField(default=True)),
                ('snacks', models.BooleanField(default=True)),
                ('dinner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='mon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(default=True)),
                ('lunch', models.BooleanField(default=True)),
                ('snacks', models.BooleanField(default=True)),
                ('dinner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='sat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(default=True)),
                ('lunch', models.BooleanField(default=True)),
                ('snacks', models.BooleanField(default=True)),
                ('dinner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='thu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(default=True)),
                ('lunch', models.BooleanField(default=True)),
                ('snacks', models.BooleanField(default=True)),
                ('dinner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='tue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(default=True)),
                ('lunch', models.BooleanField(default=True)),
                ('snacks', models.BooleanField(default=True)),
                ('dinner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='wed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(default=True)),
                ('lunch', models.BooleanField(default=True)),
                ('snacks', models.BooleanField(default=True)),
                ('dinner', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='select_food',
            name='friday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.fri'),
        ),
        migrations.AlterField(
            model_name='select_food',
            name='monday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mon'),
        ),
        migrations.AlterField(
            model_name='select_food',
            name='saturday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sat'),
        ),
        migrations.AlterField(
            model_name='select_food',
            name='thursday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.thu'),
        ),
        migrations.AlterField(
            model_name='select_food',
            name='tuesday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tue'),
        ),
        migrations.AlterField(
            model_name='select_food',
            name='wednesday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wed'),
        ),
    ]
